### ISSUE TITLE
suunto apps

### ISSUE THREAD

**Issue by sakoula** [hefler/SuuntoApps#1]
Hi there! Sorry for asking this on github, I do not seem to find any info anywhere. Do you know if it is still possible to program apps for the ambit watches. It seems that using suuntolink I can upload to the watch existing apps still in 2023!

Thanks!

<img width="474" alt="image" src="https://github.com/hefler/SuuntoApps/assets/1192173/38255f01-f7ac-4362-bd63-b690cee8367e">

**Comment by hefler** [comment]
Hi @sakoula! Sorry, I don't know. I've switched to Garmin watches… Perhaps it might be best to ask Suunto support?

**Comment by sakoula** [comment]
thanks!!!! I will ask suunto!
